name: Run Python script at 8 PM
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:  # Allows manual triggering of the workflow
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 gspread google-auth 
      - name: Create credentials file from secret
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          echo "$CREDENTIALS_JSON" > credentials.json
      - name: Run Python script
        run: python main.py
