name: Run Python script every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 gspread google-auth 

      - name: Create credentials file
        run: |
          mkdir -p /home/runner/.config
          echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > /home/runner/.config/credentials.json

      - name: Debug - Check credentials file
        run: |
          echo "Credentials file exists:"
          test -f /home/runner/.config/credentials.json && echo "Yes" || echo "No"
          echo "Credentials file size:"
          wc -c /home/runner/.config/credentials.json || echo "File not found"
          echo "First few lines of credentials file (be careful not to expose sensitive data):"
          head -n 3 /home/runner/.config/credentials.json

      - name: Run Python script
        run: python main.py
