name: Run Python script every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 gspread google-auth 

      - name: Create credentials file
        run: |
          echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' | sed 's/\\n/\n/g' > credentials.json  

      - name: Verify credentials file
        run: |
          cat ~/.config/credentials.json  

      - name: Run Python script
        run: |
          python main.py
